#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUAN_LI_QUAN_CAPHE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlQuanCaFe")]
	public partial class database_MatHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietPhieuNhapKho(ChiTietPhieuNhapKho instance);
    partial void UpdateChiTietPhieuNhapKho(ChiTietPhieuNhapKho instance);
    partial void DeleteChiTietPhieuNhapKho(ChiTietPhieuNhapKho instance);
    partial void InsertSanPhamDinhKem(SanPhamDinhKem instance);
    partial void UpdateSanPhamDinhKem(SanPhamDinhKem instance);
    partial void DeleteSanPhamDinhKem(SanPhamDinhKem instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertDanhMucSanPham(DanhMucSanPham instance);
    partial void UpdateDanhMucSanPham(DanhMucSanPham instance);
    partial void DeleteDanhMucSanPham(DanhMucSanPham instance);
    partial void InsertHangTonKho(HangTonKho instance);
    partial void UpdateHangTonKho(HangTonKho instance);
    partial void DeleteHangTonKho(HangTonKho instance);
    partial void InsertHangTonKhoSanPham(HangTonKhoSanPham instance);
    partial void UpdateHangTonKhoSanPham(HangTonKhoSanPham instance);
    partial void DeleteHangTonKhoSanPham(HangTonKhoSanPham instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertHoaDonChiTiet(HoaDonChiTiet instance);
    partial void UpdateHoaDonChiTiet(HoaDonChiTiet instance);
    partial void DeleteHoaDonChiTiet(HoaDonChiTiet instance);
    partial void InsertPhieuNhapKho(PhieuNhapKho instance);
    partial void UpdatePhieuNhapKho(PhieuNhapKho instance);
    partial void DeletePhieuNhapKho(PhieuNhapKho instance);
    partial void InsertNguyenLieu(NguyenLieu instance);
    partial void UpdateNguyenLieu(NguyenLieu instance);
    partial void DeleteNguyenLieu(NguyenLieu instance);
    partial void InsertPhuongThucThanhToan(PhuongThucThanhToan instance);
    partial void UpdatePhuongThucThanhToan(PhuongThucThanhToan instance);
    partial void DeletePhuongThucThanhToan(PhuongThucThanhToan instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public database_MatHangDataContext() : 
				base(global::QUAN_LI_QUAN_CAPHE.Properties.Settings.Default.qlQuanCaFeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public database_MatHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public database_MatHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public database_MatHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public database_MatHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietPhieuNhapKho> ChiTietPhieuNhapKhos
		{
			get
			{
				return this.GetTable<ChiTietPhieuNhapKho>();
			}
		}
		
		public System.Data.Linq.Table<SanPhamDinhKem> SanPhamDinhKems
		{
			get
			{
				return this.GetTable<SanPhamDinhKem>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<DanhMucSanPham> DanhMucSanPhams
		{
			get
			{
				return this.GetTable<DanhMucSanPham>();
			}
		}
		
		public System.Data.Linq.Table<HangTonKho> HangTonKhos
		{
			get
			{
				return this.GetTable<HangTonKho>();
			}
		}
		
		public System.Data.Linq.Table<HangTonKhoSanPham> HangTonKhoSanPhams
		{
			get
			{
				return this.GetTable<HangTonKhoSanPham>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonChiTiet> HoaDonChiTiets
		{
			get
			{
				return this.GetTable<HoaDonChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<PhieuNhapKho> PhieuNhapKhos
		{
			get
			{
				return this.GetTable<PhieuNhapKho>();
			}
		}
		
		public System.Data.Linq.Table<NguyenLieu> NguyenLieus
		{
			get
			{
				return this.GetTable<NguyenLieu>();
			}
		}
		
		public System.Data.Linq.Table<PhuongThucThanhToan> PhuongThucThanhToans
		{
			get
			{
				return this.GetTable<PhuongThucThanhToan>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuNhapKho")]
	public partial class ChiTietPhieuNhapKho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhieuNhap;
		
		private int _MaNguyenLieu;
		
		private System.Nullable<int> _SoLuongNhap;
		
		private EntityRef<PhieuNhapKho> _PhieuNhapKho;
		
		private EntityRef<NguyenLieu> _NguyenLieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuNhapChanging(int value);
    partial void OnMaPhieuNhapChanged();
    partial void OnMaNguyenLieuChanging(int value);
    partial void OnMaNguyenLieuChanged();
    partial void OnSoLuongNhapChanging(System.Nullable<int> value);
    partial void OnSoLuongNhapChanged();
    #endregion
		
		public ChiTietPhieuNhapKho()
		{
			this._PhieuNhapKho = default(EntityRef<PhieuNhapKho>);
			this._NguyenLieu = default(EntityRef<NguyenLieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuNhap", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhieuNhap
		{
			get
			{
				return this._MaPhieuNhap;
			}
			set
			{
				if ((this._MaPhieuNhap != value))
				{
					if (this._PhieuNhapKho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuNhapChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuNhap = value;
					this.SendPropertyChanged("MaPhieuNhap");
					this.OnMaPhieuNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguyenLieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNguyenLieu
		{
			get
			{
				return this._MaNguyenLieu;
			}
			set
			{
				if ((this._MaNguyenLieu != value))
				{
					if (this._NguyenLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._MaNguyenLieu = value;
					this.SendPropertyChanged("MaNguyenLieu");
					this.OnMaNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNhap", DbType="Int")]
		public System.Nullable<int> SoLuongNhap
		{
			get
			{
				return this._SoLuongNhap;
			}
			set
			{
				if ((this._SoLuongNhap != value))
				{
					this.OnSoLuongNhapChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNhap = value;
					this.SendPropertyChanged("SoLuongNhap");
					this.OnSoLuongNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhapKho_ChiTietPhieuNhapKho", Storage="_PhieuNhapKho", ThisKey="MaPhieuNhap", OtherKey="MaPhieuNhap", IsForeignKey=true)]
		public PhieuNhapKho PhieuNhapKho
		{
			get
			{
				return this._PhieuNhapKho.Entity;
			}
			set
			{
				PhieuNhapKho previousValue = this._PhieuNhapKho.Entity;
				if (((previousValue != value) 
							|| (this._PhieuNhapKho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuNhapKho.Entity = null;
						previousValue.ChiTietPhieuNhapKhos.Remove(this);
					}
					this._PhieuNhapKho.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuNhapKhos.Add(this);
						this._MaPhieuNhap = value.MaPhieuNhap;
					}
					else
					{
						this._MaPhieuNhap = default(int);
					}
					this.SendPropertyChanged("PhieuNhapKho");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguyenLieu_ChiTietPhieuNhapKho", Storage="_NguyenLieu", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu", IsForeignKey=true)]
		public NguyenLieu NguyenLieu
		{
			get
			{
				return this._NguyenLieu.Entity;
			}
			set
			{
				NguyenLieu previousValue = this._NguyenLieu.Entity;
				if (((previousValue != value) 
							|| (this._NguyenLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguyenLieu.Entity = null;
						previousValue.ChiTietPhieuNhapKhos.Remove(this);
					}
					this._NguyenLieu.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuNhapKhos.Add(this);
						this._MaNguyenLieu = value.MaNguyenLieu;
					}
					else
					{
						this._MaNguyenLieu = default(int);
					}
					this.SendPropertyChanged("NguyenLieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPhamDinhKem")]
	public partial class SanPhamDinhKem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _STT;
		
		private int _MaHangHoa;
		
		private string _TenHangHoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(System.Nullable<int> value);
    partial void OnSTTChanged();
    partial void OnMaHangHoaChanging(int value);
    partial void OnMaHangHoaChanged();
    partial void OnTenHangHoaChanging(string value);
    partial void OnTenHangHoaChanged();
    #endregion
		
		public SanPhamDinhKem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangHoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHangHoa
		{
			get
			{
				return this._MaHangHoa;
			}
			set
			{
				if ((this._MaHangHoa != value))
				{
					this.OnMaHangHoaChanging(value);
					this.SendPropertyChanging();
					this._MaHangHoa = value;
					this.SendPropertyChanged("MaHangHoa");
					this.OnMaHangHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHangHoa", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenHangHoa
		{
			get
			{
				return this._TenHangHoa;
			}
			set
			{
				if ((this._TenHangHoa != value))
				{
					this.OnTenHangHoaChanging(value);
					this.SendPropertyChanging();
					this._TenHangHoa = value;
					this.SendPropertyChanged("TenHangHoa");
					this.OnTenHangHoaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSP;
		
		private string _TenSP;
		
		private System.Nullable<char> _MaDMSP;
		
		private string _HinhAnh;
		
		private double _Gia;
		
		private EntitySet<HangTonKhoSanPham> _HangTonKhoSanPhams;
		
		private EntitySet<HoaDonChiTiet> _HoaDonChiTiets;
		
		private EntityRef<DanhMucSanPham> _DanhMucSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnMaDMSPChanging(System.Nullable<char> value);
    partial void OnMaDMSPChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnGiaChanging(double value);
    partial void OnGiaChanged();
    #endregion
		
		public SanPham()
		{
			this._HangTonKhoSanPhams = new EntitySet<HangTonKhoSanPham>(new Action<HangTonKhoSanPham>(this.attach_HangTonKhoSanPhams), new Action<HangTonKhoSanPham>(this.detach_HangTonKhoSanPhams));
			this._HoaDonChiTiets = new EntitySet<HoaDonChiTiet>(new Action<HoaDonChiTiet>(this.attach_HoaDonChiTiets), new Action<HoaDonChiTiet>(this.detach_HoaDonChiTiets));
			this._DanhMucSanPham = default(EntityRef<DanhMucSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDMSP", DbType="NChar(1)")]
		public System.Nullable<char> MaDMSP
		{
			get
			{
				return this._MaDMSP;
			}
			set
			{
				if ((this._MaDMSP != value))
				{
					if (this._DanhMucSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDMSPChanging(value);
					this.SendPropertyChanging();
					this._MaDMSP = value;
					this.SendPropertyChanged("MaDMSP");
					this.OnMaDMSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float NOT NULL")]
		public double Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_HangTonKhoSanPham", Storage="_HangTonKhoSanPhams", ThisKey="MaSP", OtherKey="MaSanPham")]
		public EntitySet<HangTonKhoSanPham> HangTonKhoSanPhams
		{
			get
			{
				return this._HangTonKhoSanPhams;
			}
			set
			{
				this._HangTonKhoSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_HoaDonChiTiet", Storage="_HoaDonChiTiets", ThisKey="MaSP", OtherKey="MaSanPham")]
		public EntitySet<HoaDonChiTiet> HoaDonChiTiets
		{
			get
			{
				return this._HoaDonChiTiets;
			}
			set
			{
				this._HoaDonChiTiets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMucSanPham_SanPham", Storage="_DanhMucSanPham", ThisKey="MaDMSP", OtherKey="MaDMSP", IsForeignKey=true)]
		public DanhMucSanPham DanhMucSanPham
		{
			get
			{
				return this._DanhMucSanPham.Entity;
			}
			set
			{
				DanhMucSanPham previousValue = this._DanhMucSanPham.Entity;
				if (((previousValue != value) 
							|| (this._DanhMucSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhMucSanPham.Entity = null;
						previousValue.SanPhams.Remove(this);
					}
					this._DanhMucSanPham.Entity = value;
					if ((value != null))
					{
						value.SanPhams.Add(this);
						this._MaDMSP = value.MaDMSP;
					}
					else
					{
						this._MaDMSP = default(Nullable<char>);
					}
					this.SendPropertyChanged("DanhMucSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HangTonKhoSanPhams(HangTonKhoSanPham entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_HangTonKhoSanPhams(HangTonKhoSanPham entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
		
		private void attach_HoaDonChiTiets(HoaDonChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_HoaDonChiTiets(HoaDonChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMucSanPham")]
	public partial class DanhMucSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private char _MaDMSP;
		
		private string _TenDMSP;
		
		private EntitySet<SanPham> _SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDMSPChanging(char value);
    partial void OnMaDMSPChanged();
    partial void OnTenDMSPChanging(string value);
    partial void OnTenDMSPChanged();
    #endregion
		
		public DanhMucSanPham()
		{
			this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDMSP", DbType="NChar(1) NOT NULL", IsPrimaryKey=true)]
		public char MaDMSP
		{
			get
			{
				return this._MaDMSP;
			}
			set
			{
				if ((this._MaDMSP != value))
				{
					this.OnMaDMSPChanging(value);
					this.SendPropertyChanging();
					this._MaDMSP = value;
					this.SendPropertyChanged("MaDMSP");
					this.OnMaDMSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDMSP", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenDMSP
		{
			get
			{
				return this._TenDMSP;
			}
			set
			{
				if ((this._TenDMSP != value))
				{
					this.OnTenDMSPChanging(value);
					this.SendPropertyChanging();
					this._TenDMSP = value;
					this.SendPropertyChanged("TenDMSP");
					this.OnTenDMSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMucSanPham_SanPham", Storage="_SanPhams", ThisKey="MaDMSP", OtherKey="MaDMSP")]
		public EntitySet<SanPham> SanPhams
		{
			get
			{
				return this._SanPhams;
			}
			set
			{
				this._SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.DanhMucSanPham = this;
		}
		
		private void detach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.DanhMucSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangTonKho")]
	public partial class HangTonKho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHangTonKho;
		
		private System.Nullable<int> _MaNguyenLieu;
		
		private System.Nullable<int> _SoLuongTonKho;
		
		private EntitySet<HangTonKhoSanPham> _HangTonKhoSanPhams;
		
		private EntityRef<NguyenLieu> _NguyenLieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangTonKhoChanging(int value);
    partial void OnMaHangTonKhoChanged();
    partial void OnMaNguyenLieuChanging(System.Nullable<int> value);
    partial void OnMaNguyenLieuChanged();
    partial void OnSoLuongTonKhoChanging(System.Nullable<int> value);
    partial void OnSoLuongTonKhoChanged();
    #endregion
		
		public HangTonKho()
		{
			this._HangTonKhoSanPhams = new EntitySet<HangTonKhoSanPham>(new Action<HangTonKhoSanPham>(this.attach_HangTonKhoSanPhams), new Action<HangTonKhoSanPham>(this.detach_HangTonKhoSanPhams));
			this._NguyenLieu = default(EntityRef<NguyenLieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangTonKho", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHangTonKho
		{
			get
			{
				return this._MaHangTonKho;
			}
			set
			{
				if ((this._MaHangTonKho != value))
				{
					this.OnMaHangTonKhoChanging(value);
					this.SendPropertyChanging();
					this._MaHangTonKho = value;
					this.SendPropertyChanged("MaHangTonKho");
					this.OnMaHangTonKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguyenLieu", DbType="Int")]
		public System.Nullable<int> MaNguyenLieu
		{
			get
			{
				return this._MaNguyenLieu;
			}
			set
			{
				if ((this._MaNguyenLieu != value))
				{
					if (this._NguyenLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._MaNguyenLieu = value;
					this.SendPropertyChanged("MaNguyenLieu");
					this.OnMaNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTonKho", DbType="Int")]
		public System.Nullable<int> SoLuongTonKho
		{
			get
			{
				return this._SoLuongTonKho;
			}
			set
			{
				if ((this._SoLuongTonKho != value))
				{
					this.OnSoLuongTonKhoChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTonKho = value;
					this.SendPropertyChanged("SoLuongTonKho");
					this.OnSoLuongTonKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangTonKho_HangTonKhoSanPham", Storage="_HangTonKhoSanPhams", ThisKey="MaHangTonKho", OtherKey="MaHangTonKho")]
		public EntitySet<HangTonKhoSanPham> HangTonKhoSanPhams
		{
			get
			{
				return this._HangTonKhoSanPhams;
			}
			set
			{
				this._HangTonKhoSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguyenLieu_HangTonKho", Storage="_NguyenLieu", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu", IsForeignKey=true)]
		public NguyenLieu NguyenLieu
		{
			get
			{
				return this._NguyenLieu.Entity;
			}
			set
			{
				NguyenLieu previousValue = this._NguyenLieu.Entity;
				if (((previousValue != value) 
							|| (this._NguyenLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguyenLieu.Entity = null;
						previousValue.HangTonKhos.Remove(this);
					}
					this._NguyenLieu.Entity = value;
					if ((value != null))
					{
						value.HangTonKhos.Add(this);
						this._MaNguyenLieu = value.MaNguyenLieu;
					}
					else
					{
						this._MaNguyenLieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("NguyenLieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HangTonKhoSanPhams(HangTonKhoSanPham entity)
		{
			this.SendPropertyChanging();
			entity.HangTonKho = this;
		}
		
		private void detach_HangTonKhoSanPhams(HangTonKhoSanPham entity)
		{
			this.SendPropertyChanging();
			entity.HangTonKho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangTonKhoSanPham")]
	public partial class HangTonKhoSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHangTonKho;
		
		private int _MaSanPham;
		
		private System.Nullable<int> _SoLuongTonKho;
		
		private EntityRef<HangTonKho> _HangTonKho;
		
		private EntityRef<SanPham> _SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangTonKhoChanging(int value);
    partial void OnMaHangTonKhoChanged();
    partial void OnMaSanPhamChanging(int value);
    partial void OnMaSanPhamChanged();
    partial void OnSoLuongTonKhoChanging(System.Nullable<int> value);
    partial void OnSoLuongTonKhoChanged();
    #endregion
		
		public HangTonKhoSanPham()
		{
			this._HangTonKho = default(EntityRef<HangTonKho>);
			this._SanPham = default(EntityRef<SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangTonKho", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHangTonKho
		{
			get
			{
				return this._MaHangTonKho;
			}
			set
			{
				if ((this._MaHangTonKho != value))
				{
					if (this._HangTonKho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHangTonKhoChanging(value);
					this.SendPropertyChanging();
					this._MaHangTonKho = value;
					this.SendPropertyChanged("MaHangTonKho");
					this.OnMaHangTonKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTonKho", DbType="Int")]
		public System.Nullable<int> SoLuongTonKho
		{
			get
			{
				return this._SoLuongTonKho;
			}
			set
			{
				if ((this._SoLuongTonKho != value))
				{
					this.OnSoLuongTonKhoChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTonKho = value;
					this.SendPropertyChanged("SoLuongTonKho");
					this.OnSoLuongTonKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangTonKho_HangTonKhoSanPham", Storage="_HangTonKho", ThisKey="MaHangTonKho", OtherKey="MaHangTonKho", IsForeignKey=true)]
		public HangTonKho HangTonKho
		{
			get
			{
				return this._HangTonKho.Entity;
			}
			set
			{
				HangTonKho previousValue = this._HangTonKho.Entity;
				if (((previousValue != value) 
							|| (this._HangTonKho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangTonKho.Entity = null;
						previousValue.HangTonKhoSanPhams.Remove(this);
					}
					this._HangTonKho.Entity = value;
					if ((value != null))
					{
						value.HangTonKhoSanPhams.Add(this);
						this._MaHangTonKho = value.MaHangTonKho;
					}
					else
					{
						this._MaHangTonKho = default(int);
					}
					this.SendPropertyChanged("HangTonKho");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_HangTonKhoSanPham", Storage="_SanPham", ThisKey="MaSanPham", OtherKey="MaSP", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.HangTonKhoSanPhams.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.HangTonKhoSanPhams.Add(this);
						this._MaSanPham = value.MaSP;
					}
					else
					{
						this._MaSanPham = default(int);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHoaDon;
		
		private System.DateTime _NgayHoaDon;
		
		private double _TongTien;
		
		private EntitySet<HoaDonChiTiet> _HoaDonChiTiets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(int value);
    partial void OnMaHoaDonChanged();
    partial void OnNgayHoaDonChanging(System.DateTime value);
    partial void OnNgayHoaDonChanged();
    partial void OnTongTienChanging(double value);
    partial void OnTongTienChanged();
    #endregion
		
		public HoaDon()
		{
			this._HoaDonChiTiets = new EntitySet<HoaDonChiTiet>(new Action<HoaDonChiTiet>(this.attach_HoaDonChiTiets), new Action<HoaDonChiTiet>(this.detach_HoaDonChiTiets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHoaDon", DbType="Date NOT NULL")]
		public System.DateTime NgayHoaDon
		{
			get
			{
				return this._NgayHoaDon;
			}
			set
			{
				if ((this._NgayHoaDon != value))
				{
					this.OnNgayHoaDonChanging(value);
					this.SendPropertyChanging();
					this._NgayHoaDon = value;
					this.SendPropertyChanged("NgayHoaDon");
					this.OnNgayHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float NOT NULL")]
		public double TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_HoaDonChiTiet", Storage="_HoaDonChiTiets", ThisKey="MaHoaDon", OtherKey="MaHoaDon")]
		public EntitySet<HoaDonChiTiet> HoaDonChiTiets
		{
			get
			{
				return this._HoaDonChiTiets;
			}
			set
			{
				this._HoaDonChiTiets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonChiTiets(HoaDonChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_HoaDonChiTiets(HoaDonChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonChiTiet")]
	public partial class HoaDonChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHoaDon;
		
		private int _MaSanPham;
		
		private string _TenSanPham;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _GiaBan;
		
		private System.Nullable<double> _ThanhTien;
		
		private System.Nullable<int> _TongSoLuong;
		
		private System.Nullable<double> _TongTien;
		
		private System.Nullable<int> _SoGoiNuoc;
		
		private EntityRef<HoaDon> _HoaDon;
		
		private EntityRef<SanPham> _SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(int value);
    partial void OnMaHoaDonChanged();
    partial void OnMaSanPhamChanging(int value);
    partial void OnMaSanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaBanChanging(System.Nullable<decimal> value);
    partial void OnGiaBanChanged();
    partial void OnThanhTienChanging(System.Nullable<double> value);
    partial void OnThanhTienChanged();
    partial void OnTongSoLuongChanging(System.Nullable<int> value);
    partial void OnTongSoLuongChanged();
    partial void OnTongTienChanging(System.Nullable<double> value);
    partial void OnTongTienChanged();
    partial void OnSoGoiNuocChanging(System.Nullable<int> value);
    partial void OnSoGoiNuocChanged();
    #endregion
		
		public HoaDonChiTiet()
		{
			this._HoaDon = default(EntityRef<HoaDon>);
			this._SanPham = default(EntityRef<SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(255)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float")]
		public System.Nullable<double> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoLuong", DbType="Int")]
		public System.Nullable<int> TongSoLuong
		{
			get
			{
				return this._TongSoLuong;
			}
			set
			{
				if ((this._TongSoLuong != value))
				{
					this.OnTongSoLuongChanging(value);
					this.SendPropertyChanging();
					this._TongSoLuong = value;
					this.SendPropertyChanged("TongSoLuong");
					this.OnTongSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGoiNuoc", DbType="Int")]
		public System.Nullable<int> SoGoiNuoc
		{
			get
			{
				return this._SoGoiNuoc;
			}
			set
			{
				if ((this._SoGoiNuoc != value))
				{
					this.OnSoGoiNuocChanging(value);
					this.SendPropertyChanging();
					this._SoGoiNuoc = value;
					this.SendPropertyChanged("SoGoiNuoc");
					this.OnSoGoiNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_HoaDonChiTiet", Storage="_HoaDon", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.HoaDonChiTiets.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.HoaDonChiTiets.Add(this);
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(int);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_HoaDonChiTiet", Storage="_SanPham", ThisKey="MaSanPham", OtherKey="MaSP", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.HoaDonChiTiets.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.HoaDonChiTiets.Add(this);
						this._MaSanPham = value.MaSP;
					}
					else
					{
						this._MaSanPham = default(int);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuNhapKho")]
	public partial class PhieuNhapKho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhieuNhap;
		
		private System.DateTime _NgayNhap;
		
		private string _NguoiNhap;
		
		private string _GhiChu;
		
		private EntitySet<ChiTietPhieuNhapKho> _ChiTietPhieuNhapKhos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuNhapChanging(int value);
    partial void OnMaPhieuNhapChanged();
    partial void OnNgayNhapChanging(System.DateTime value);
    partial void OnNgayNhapChanged();
    partial void OnNguoiNhapChanging(string value);
    partial void OnNguoiNhapChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public PhieuNhapKho()
		{
			this._ChiTietPhieuNhapKhos = new EntitySet<ChiTietPhieuNhapKho>(new Action<ChiTietPhieuNhapKho>(this.attach_ChiTietPhieuNhapKhos), new Action<ChiTietPhieuNhapKho>(this.detach_ChiTietPhieuNhapKhos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuNhap", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhieuNhap
		{
			get
			{
				return this._MaPhieuNhap;
			}
			set
			{
				if ((this._MaPhieuNhap != value))
				{
					this.OnMaPhieuNhapChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuNhap = value;
					this.SendPropertyChanged("MaPhieuNhap");
					this.OnMaPhieuNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="Date NOT NULL")]
		public System.DateTime NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiNhap", DbType="NVarChar(100)")]
		public string NguoiNhap
		{
			get
			{
				return this._NguoiNhap;
			}
			set
			{
				if ((this._NguoiNhap != value))
				{
					this.OnNguoiNhapChanging(value);
					this.SendPropertyChanging();
					this._NguoiNhap = value;
					this.SendPropertyChanged("NguoiNhap");
					this.OnNguoiNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhapKho_ChiTietPhieuNhapKho", Storage="_ChiTietPhieuNhapKhos", ThisKey="MaPhieuNhap", OtherKey="MaPhieuNhap")]
		public EntitySet<ChiTietPhieuNhapKho> ChiTietPhieuNhapKhos
		{
			get
			{
				return this._ChiTietPhieuNhapKhos;
			}
			set
			{
				this._ChiTietPhieuNhapKhos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuNhapKhos(ChiTietPhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhapKho = this;
		}
		
		private void detach_ChiTietPhieuNhapKhos(ChiTietPhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhapKho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguyenLieu")]
	public partial class NguyenLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNguyenLieu;
		
		private string _TenNguyenLieu;
		
		private string _DonViTinh;
		
		private System.Nullable<int> _SoLuongTonKho;
		
		private EntitySet<ChiTietPhieuNhapKho> _ChiTietPhieuNhapKhos;
		
		private EntitySet<HangTonKho> _HangTonKhos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguyenLieuChanging(int value);
    partial void OnMaNguyenLieuChanged();
    partial void OnTenNguyenLieuChanging(string value);
    partial void OnTenNguyenLieuChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnSoLuongTonKhoChanging(System.Nullable<int> value);
    partial void OnSoLuongTonKhoChanged();
    #endregion
		
		public NguyenLieu()
		{
			this._ChiTietPhieuNhapKhos = new EntitySet<ChiTietPhieuNhapKho>(new Action<ChiTietPhieuNhapKho>(this.attach_ChiTietPhieuNhapKhos), new Action<ChiTietPhieuNhapKho>(this.detach_ChiTietPhieuNhapKhos));
			this._HangTonKhos = new EntitySet<HangTonKho>(new Action<HangTonKho>(this.attach_HangTonKhos), new Action<HangTonKho>(this.detach_HangTonKhos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguyenLieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNguyenLieu
		{
			get
			{
				return this._MaNguyenLieu;
			}
			set
			{
				if ((this._MaNguyenLieu != value))
				{
					this.OnMaNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._MaNguyenLieu = value;
					this.SendPropertyChanged("MaNguyenLieu");
					this.OnMaNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguyenLieu", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenNguyenLieu
		{
			get
			{
				return this._TenNguyenLieu;
			}
			set
			{
				if ((this._TenNguyenLieu != value))
				{
					this.OnTenNguyenLieuChanging(value);
					this.SendPropertyChanging();
					this._TenNguyenLieu = value;
					this.SendPropertyChanged("TenNguyenLieu");
					this.OnTenNguyenLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTonKho", DbType="Int")]
		public System.Nullable<int> SoLuongTonKho
		{
			get
			{
				return this._SoLuongTonKho;
			}
			set
			{
				if ((this._SoLuongTonKho != value))
				{
					this.OnSoLuongTonKhoChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTonKho = value;
					this.SendPropertyChanged("SoLuongTonKho");
					this.OnSoLuongTonKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguyenLieu_ChiTietPhieuNhapKho", Storage="_ChiTietPhieuNhapKhos", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu")]
		public EntitySet<ChiTietPhieuNhapKho> ChiTietPhieuNhapKhos
		{
			get
			{
				return this._ChiTietPhieuNhapKhos;
			}
			set
			{
				this._ChiTietPhieuNhapKhos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguyenLieu_HangTonKho", Storage="_HangTonKhos", ThisKey="MaNguyenLieu", OtherKey="MaNguyenLieu")]
		public EntitySet<HangTonKho> HangTonKhos
		{
			get
			{
				return this._HangTonKhos;
			}
			set
			{
				this._HangTonKhos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuNhapKhos(ChiTietPhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.NguyenLieu = this;
		}
		
		private void detach_ChiTietPhieuNhapKhos(ChiTietPhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.NguyenLieu = null;
		}
		
		private void attach_HangTonKhos(HangTonKho entity)
		{
			this.SendPropertyChanging();
			entity.NguyenLieu = this;
		}
		
		private void detach_HangTonKhos(HangTonKho entity)
		{
			this.SendPropertyChanging();
			entity.NguyenLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhuongThucThanhToan")]
	public partial class PhuongThucThanhToan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhuongThuc;
		
		private string _TenPhuongThuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhuongThucChanging(int value);
    partial void OnMaPhuongThucChanged();
    partial void OnTenPhuongThucChanging(string value);
    partial void OnTenPhuongThucChanged();
    #endregion
		
		public PhuongThucThanhToan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuongThuc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhuongThuc
		{
			get
			{
				return this._MaPhuongThuc;
			}
			set
			{
				if ((this._MaPhuongThuc != value))
				{
					this.OnMaPhuongThucChanging(value);
					this.SendPropertyChanging();
					this._MaPhuongThuc = value;
					this.SendPropertyChanged("MaPhuongThuc");
					this.OnMaPhuongThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhuongThuc", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenPhuongThuc
		{
			get
			{
				return this._TenPhuongThuc;
			}
			set
			{
				if ((this._TenPhuongThuc != value))
				{
					this.OnTenPhuongThucChanging(value);
					this.SendPropertyChanging();
					this._TenPhuongThuc = value;
					this.SendPropertyChanged("TenPhuongThuc");
					this.OnTenPhuongThucChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenHienThi;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _SoDienThoai;
		
		private string _Gmail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenHienThiChanging(string value);
    partial void OnTenHienThiChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnGmailChanging(string value);
    partial void OnGmailChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHienThi", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string TenHienThi
		{
			get
			{
				return this._TenHienThi;
			}
			set
			{
				if ((this._TenHienThi != value))
				{
					this.OnTenHienThiChanging(value);
					this.SendPropertyChanging();
					this._TenHienThi = value;
					this.SendPropertyChanged("TenHienThi");
					this.OnTenHienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gmail
		{
			get
			{
				return this._Gmail;
			}
			set
			{
				if ((this._Gmail != value))
				{
					this.OnGmailChanging(value);
					this.SendPropertyChanging();
					this._Gmail = value;
					this.SendPropertyChanged("Gmail");
					this.OnGmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
